using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace VarsWebApi.Models
{
    /// <summary>
    /// สัญชาติ 
    /// </summary>
    public enum Nationality
    {
        /// <summary>
        /// ไทย
        /// </summary>
        Code_Thailand = 764,

        /// <summary>
        /// พม่า
        /// </summary>
        Code_Myanmar = 104,

        Code_Cambodia = 116,
        Code_Laos = 418,
        Code_China = 156,
        Code_India = 356,
        Code_UnitedKingdomEnglish_ = 826,
        Code_Germany = 276,
        Code_Philippines = 608,
        Code_Vietnam = 704,
        Code_Japanese = 392,
        Code_USA = 840,
        Code_Qatar = 634,
        Code_Kazakhstan = 398,
        Code_Kyrgyzstan = 417,
        Code_Kuwait = 414,
        Code_Georgia = 268,
        Code_Jordan = 400,
        Code_SaudiArabia = 682,
        Code_Cyprus = 196,
        Code_Palestine = 275,
        Code_TimorLeste = 626,
        Code_Turkey = 792,
        Code_Turkmenistan = 795,
        Code_Taiwan = 888,
        Code_Tajikistan = 762,
        Code_Nepal = 524,
        Code_Brunei = 096,
        Code_Bangladesh = 050,
        Code_Bahrain = 048,
        Code_Pakistan = 586,
        Code_Bhutan = 064,
        Code_Mongolia = 496,
        Code_Maldives = 462,
        Code_Macau = 446,
        Code_Malaysia = 458,
        Code_Yemen = 887,
        Code_Lebanon = 422,
        Code_SriLanka = 144,
        Code_ArabEmirates = 784,
        Code_SouthKorea = 410,
        Code_NorthKorea = 408,
        Code_SyrianArab = 760,
        Code_Singapore = 702,
        Code_Afghanistan = 004,
        Code_Azerbaijan = 031,
        Code_Armenia = 051,
        Code_Indonesia = 360,
        Code_Iraq = 368,
        Code_Israel = 376,
        Code_Iran = 364,
        Code_Uzbekistan = 860,
        Code_Oman = 512,
        Code_HongKong = 344,
        Code_Guernsey = 831,
        Code_Greece = 300,
        Code_Greenland = 304,
        Code_Guadeloupe = 312,
        Code_Manx = 833,
        Code_Croatia = 191,
        Code_Jersey = 832,
        Code_SanMarino = 674,
        Code_SaintHelena = 654,
        Code_Serbia_Montenegro = 891,
        Code_SaintPierre_Miquelon = 666,
        Code_Denmark = 208,
        Code_Norway = 578,
        Code_NewCaledonia = 540,
        Code_Netherlands = 528,
        Code_NetherlandsAntilles = 530,
        Code_Bosnia_Herzegovina = 070,
        Code_Bulgaria = 100,
        Code_Belgium = 056,
        Code_Belarus = 112,
        Code_Bermuda = 060,
        Code_Portugal = 620,
        Code_Poland = 616,
        Code_France = 250,
        Code_Pitcairn = 612,
        Code_Finland = 246,
        Code_FrenchGuiana = 254,
        Code_FrenchPolynesia = 258,
        Code_Montserrat = 500,
        Code_Malta = 470,
        Code_Mayotte = 175,
        Code_Martinique = 474,
        Code_Monaco = 492,
        Code_Gibraltar = 292,
        Code_Ukraine = 804,
        Code_Reunion = 638,
        Code_Romania = 642,
        Code_Luxembourg = 442,
        Code_Latvia = 428,
        Code_Liechtenstein = 438,
        Code_Lithuania = 440,
        Code_Spain = 724,
        Code_Slovakia = 703,
        Code_Slovenia = 705,
        Code_Switzerland = 756,
        Code_Sweden = 752,
        Code_Russian = 643,
        Code_CzechRepublic = 203,
        Code_MoldovaRepublic = 498,
        Code_YugoslavRepublic_of_Macedonia = 807,
        Code_Channel_Islands = 830,
        Code_Turks_Caicos_Islands = 796,
        Code_BritishVirgin_Islands = 092,
        Code_Falkland_Islands = 238,
        Code_Faroe_Islands = 234,
        Code_Wallis_Futuna_Islands = 876,
        Code_Svalbard_JanMayen_Islands = 744,
        Code_Aland_Islands = 248,
        Code_Austria = 040,
        Code_Andorra = 020,
        Code_Aruba = 533,
        Code_Italy = 380,
        Code_Estonia = 233,
        Code_Anguilla = 660,
        Code_Albania = 008,
        Code_Iceland = 352,
        Code_Ireland = 372,
        Code_Holly = 336,
        Code_Hungary = 348,
        Code_Guatemala = 320,
        Code_Guyana = 328,
        Code_Grenada = 308,
        Code_CostaRica = 188,
        Code_Cuba = 192,
        Code_Colombia = 170,
        Code_Jamaica = 388,
        Code_Chile = 152,
        Code_Suriname = 740,
        Code_SaintKitts_Nevis = 659,
        Code_SaintLucia = 662,
        Code_SaintVincent_Grenadines = 670,
        Code_Dominica = 212,
        Code_Trinidad_Tobago = 780,
        Code_Nicaragua = 558,
        Code_Brazil = 076,
        Code_Barbados = 052,
        Code_Bahamas = 044,
        Code_Belize = 084,
        Code_Bolivia = 068,
        Code_Panama = 591,
        Code_Paraguay = 600,
        Code_Peru = 604,
        Code_PuertoRico = 630,
        Code_Mexico = 484,
        Code_Venezuela = 862,
        Code_DominicanRepublic = 214,
        Code_Argentina = 032,
        Code_Uruguay = 858,
        Code_Ecuador = 218,
        Code_ElSalvador = 222,
        Code_Antigua_Barbuda = 028,
        Code_Honduras = 340,
        Code_Haiti = 332,
        Code_Guam = 316,
        Code_Canada = 124,
        Code_NorthernMariana_Islands = 580,
        Code_US_Virgin_Islands = 850,
        Code_AmericanSamoa = 016,
        Code_Ghana = 288,
        Code_Gabon = 266,
        Code_Guinea = 324,
        Code_GuineaBissau = 624,
        Code_Gambia = 270,
        Code_Cote_d_Ivoire = 384,
        Code_Congo = 178,
        Code_Comoros = 174,
        Code_Kenya = 404,
        Code_CapeVerde = 132,
        Code_Cameroon = 120,
        Code_Djibouti = 262,
        Code_cinnabar = 148,
        Code_WesternSahara = 732,
        Code_Zimbabwe = 716,
        Code_Sudan = 736,
        Code_Seychelles = 690,
        Code_Senegal = 686,
        Code_SaoTome_Principe = 678,
        Code_SierraLeone = 694,
        Code_Zambia = 894,
        Code_Somalia = 706,
        Code_Tunisia = 788,
        Code_Togo = 768,
        Code_Namibia = 516,
        Code_Nigeria = 566,
        Code_Niger = 562,
        Code_Botswana = 072,
        Code_Burundi = 108,
        Code_BurkinaFaso = 854,
        Code_Benin = 204,
        Code_Mauritius = 480,
        Code_Mauritania = 478,
        Code_Madagascar = 450,
        Code_Malawi = 454,
        Code_Mali = 466,
        Code_Mozambique = 508,
        Code_Morocco = 504,
        Code_Uganda = 800,
        Code_Rwanda = 646,
        Code_Lesotho = 426,
        Code_Liberia = 430,
        Code_Swaziland = 748,
        Code_Tanzania = 834,
        Code_CongoRepublic = 180,
        Code_CentralAfricanRepublic = 140,
        Code_LibyaArabic = 434,
        Code_EquatorialGuinea = 226,
        Code_Egypt = 818,
        Code_Ethiopia = 231,
        Code_Eritrea = 232,
        Code_Angola = 024,
        Code_SouthAfrica = 710,
        Code_Algeria = 012,
        Code_NorfolkIsland = 574,
        Code_Kiribati = 296,
        Code_Samoa = 882,
        Code_Tonga = 776,
        Code_Tuvalu = 798,
        Code_Tokelau = 772,
        Code_Nauru = 520,
        Code_NewZealand = 554,
        Code_Niue = 570,
        Code_PapuaNewGuinea = 598,
        Code_Palau = 585,
        Code_Fiji = 242,
        Code_Micronesia_federal_ = 583,
        Code_Vanuatu = 548,
        Code_Cook_Islands = 184,
        Code_SolomonIslands = 090,
        Code_Marshall_Islands = 584,
        Code_Australia = 036,
        Code_Karen = 901,
        Code_Khmu = 909,
        Code_ThaiYai_Tribute_Lue = 905,
        Code_Hmong = 902,
        Code_Yao = 908,
        Code_Each = 903,
        Code_Loi = 906,
        Code_LuSu = 907,
        Code_a_Kha = 904,

        /// <summary>
        /// ไม่มีสัญชาติ
        /// </summary>
        Code_NoNationality = 998,

         /// <summary>
        /// ไม่ทราบ
        /// </summary>
        Code_Unknow = 999
    }
}